name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '35 06 * * MON' # runs weekly on Monday at 06:45

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@vX
        with:
          git-author-name: 'Anton Frost'
          git-author-email: 'anton.friberg@outlook.com'
          git-committer-name: 'Anton Frost'
          git-committer-email: 'anton.friberg@outlook.com'
